// authentication
export const USERS_LOGIN_REQUEST  = "USERS_LOGIN_REQUEST";
export const USERS_LOGIN_SUCCESS  = "USERS_LOGIN_SUCCESS";
export const USERS_LOGIN_FAILURE  = "USERS_LOGIN_FAILURE";

export const USERS_LOGOUT         = "USERS_LOGOUT";

// todos
export const ADD_TODO       = "ADD_TODO";
export const TOGGLE_TODO    = "TOGGLE_TODO";

export const LIST_TODOS_REQUEST = "LIST_TODOS_REQUEST";
export const LIST_TODOS_SUCCESS = "LIST_TODOS_SUCCESS";
export const LIST_TODOS_FAILURE = "LIST_TODOS_FAILURE";

// visibility filter
export const SET_VISIBILITY_FILTER    = 'SET_VISIBILITY_FILTER';


export const LIST_PLANS_REQUEST = "LIST_PLANS_REQUEST";
export const LIST_PLANS_SUCCESS = "LIST_PLANS_SUCCESS";
export const LIST_PLANS_FAILURE = "LIST_PLANS_FAILURE";
